---
title: "Estudo Proagro"
author: "Vitor Villarino"
date: "03/09/2019"
output: html_document
---

```{r setup_summarytools, include=FALSE}
library(knitr)
opts_chunk$set(results = 'asis',      # This is essential (can also be set at the chunk-level)
              comment = NA,
              prompt = FALSE,
              cache = FALSE,
              include=FALSE)

library(summarytools)
st_options(plain.ascii = FALSE,       # This is very handy in all Rmd documents
          style = "rmarkdown",        # This too
          footnote = NA,              # Avoids footnotes which would clutter the results
          subtitle.emphasis = FALSE   # This is a setting to experiment with - according to
)                                     # the theme used, it might improve the headings'
                                      # layout

st_css()                              # This is a must; without it, expect odd layout
```

```{r setup, include=FALSE}
library("plotly")
library("tidyverse")
library("htmlwidgets")

#https://plot.ly/r/ - ver
```


```{r load_data, include=FALSE}
source("./Scripts/01_Load_Data.R", encoding = "UTF-8")
source("./Scripts/02_Transformacoes_Necessarias.R", encoding = "UTF-8")
```


## Inflação

Usei os valores do IPCA acumulado de 12 meses (julho a julho). Peguei do site do IBGE  <https://ww2.ibge.gov.br/home/estatistica/indicadores/precos/inpc_ipca/defaultseriesHist.shtm> e no final obtive os seguintes valores

```{r inflacao_tabela}
kable(inflacao)
```








## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
